-- 매장 정보의 대한 CREATE TABLE --

-- 2. 매장 상품 정보 TABLE 생성(12월10일 수정)

CREATE TABLE SHOP_PRODUCT_TBL (
-- 매장 코드
S_CODE VARCHAR2(30) PRIMARY KEY ,
-- 고양이
P_CAT CHAR(2) DEFAULT 0,
-- 강아지
P_DOG CHAR(2) DEFAULT 0,
-- 단모(고양이)
P_SHORT CHAR(2) DEFAULT 0,
-- 장모(고양이)
P_LONG CHAR(2) DEFAULT 0,
-- 소형(강아지)
P_SMALL CHAR(2) DEFAULT 0,
-- 중형(강아지)
P_MEDIUM CHAR(2) DEFAULT 0,
-- 대형(강아지)
P_LARGE CHAR(2) DEFAULT 0);
commit;

-- 2-1. 매장 상품의 매장 코드 외래키 생성
ALTER TABLE SHOP_PRODUCT_TBL ADD CONSTRAINT 
FK_PRODUCT_S_CODE FOREIGN KEY(S_CODE)REFERENCES SHOP_INFO_TBL(S_CODE); 

commit;

SELECT * FROM SHOP_PRODUCT_TBL;

