-- 디자이너 사진 정보의 대한 CREATE TABLE --

-- 5. 디자이너 사진 정보 TABLE

CREATE TABLE SHOP_DESIGNER_PHOTO_TBL (
-- 디자이너 코드
D_CODE VARCHAR2(30) NOT NULL,
-- 디자이너 사진 경로 
D_PHOTOPATH VARCHAR2(500) NOT NULL,
-- 디자이너 사진 파일이름(파일이름 중복되지 않는 규칙 부여 필요)
D_PHOTONAME VARCHAR2(100) NOT NULL,
-- 디자이너 사진 파일 원래 이름 명
D_PHOTONAME_ORIGIN VARCHAR2(100) NOT NULL); 

commit;

-- 5-1. 디자이너의 코드 외래키 생성

ALTER TABLE SHOP_DESIGNER_PHOTO_TBL ADD CONSTRAINT
FK_SHOP_DESIGNER_PHOTO_CODE FOREIGN KEY(D_CODE)REFERENCES 
SHOP_DESIGNER_TBL(D_CODE);
commit;

