-- 매장 정보의 대한 CREATE TABLE --

-- 2. 매장 상품 정보 TABLE 생성

CREATE TABLE SHOP_PRODUCT_TBL (
-- 매장 코드
S_CODE VARCHAR2(30),
-- 상품 코드
P_CODE VARCHAR2(30) NOT NULL PRIMARY KEY,
-- 종분류 강아지/고양이
P_KIND VARCHAR2(30) NOT NULL,
-- 상품구분 강아지(소형, 중형, 대형) 고양이(단모, 장모)
P_GRADE VARCHAR2(30),
-- 상품의 이름(구매쪽에서 사용) 제거여부 확인 필요
P_NAME VARCHAR2(30) NOT NULL,
-- 상품 가격
P_PRICE NUMBER(10));
commit;

-- 2-1. 매장 상품의 매장 코드 외래키 생성
ALTER TABLE SHOP_PRODUCT_TBL ADD CONSTRAINT 
FK_PRODUCT_S_CODE FOREIGN KEY(S_CODE)REFERENCES SHOP_INFO_TBL(S_CODE);

-- 2-2. 매장 상품 코드의 SEQUENCE
CREATE SEQUENCE SHOP_PRODUCT_TBL_SEQ
	START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999
    NOCYCLE; 
    commit;
    
-- 매장 코드 SEQUENCE TEST용 CONCAT으로 "고정문자열"+SEQUENCE
INSERT INTO SHOP_PRODUCT_TBL (S_CODE,P_CODE,P_KIND,
P_GRADE,P_NAME,P_PRICE) VALUES
('CNDSHOP_1',CONCAT('CNDPRODUCT_',SHOP_PRODUCT_TBL_SEQ.NEXTVAL),
'강아지','소형','곰돌이',50000);

commit;

SELECT * FROM SHOP_PRODUCT_TBL;

